{"id": "CVE-2009-5010", "product": "n/a", "version": "n/a", "vulnerability": ["n/a"], "description": "Race condition in the FTPHandler class in ftpserver.py in pyftpdlib before 0.5.1 allows remote attackers to cause a denial of service (daemon outage) by establishing and then immediately closing a TCP connection, leading to the accept function having an unexpected return value of None, a different vulnerability than CVE-2010-3494.", "poc": {"reference": ["http://code.google.com/p/pyftpdlib/source/browse/trunk/HISTORY"], "github": ["No PoCs found on GitHub currently."]}}