{
    "id": "CVE-2019-9948",
    "product": "n/a",
    "version": "n/a ",
    "vulnerability": [
        "n/a"
    ],
    "description": "urllib in Python 2.x through 2.7.16 supports the local_file: scheme, which makes it easier for remote attackers to bypass protection mechanisms that blacklist file: URIs, as demonstrated by triggering a urllib.urlopen('local_file:///etc/passwd') call.",
    "poc": {
        "reference": [
            "http://packetstormsecurity.com/files/154927/Slackware-Security-Advisory-python-Updates.html",
            "https://bugs.python.org/issue35907",
            "https://usn.ubuntu.com/4127-2/"
        ],
        "github": [
            "https://github.com/ARPSyndicate/cvemon"
        ]
    }
}