{
    "id": "CVE-2015-3206",
    "product": "n/a",
    "version": "n/a ",
    "vulnerability": [
        "n/a"
    ],
    "description": "The checkPassword function in python-kerberos does not authenticate the KDC it attempts to communicate with, which allows remote attackers to cause a denial of service (bad response), or have other unspecified impact by performing a man-in-the-middle attack.",
    "poc": {
        "reference": [
            "https://github.com/apple/ccs-pykerberos/issues/31"
        ],
        "github": [
            "No PoCs found on GitHub currently."
        ]
    }
}