{"id": "CVE-2020-35917", "product": "n/a", "version": "n/a", "vulnerability": ["n/a"], "description": "An issue was discovered in the pyo3 crate before 0.12.4 for Rust. There is a reference-counting error and use-after-free in From<Py<T>>.", "poc": {"reference": ["No PoCs from references."], "github": ["https://github.com/Artisan-Lab/Rust-memory-safety-bugs"]}}