{"id": "CVE-2020-24584", "product": "n/a", "version": "n/a", "vulnerability": ["n/a"], "description": "An issue was discovered in Django 2.2 before 2.2.16, 3.0 before 3.0.10, and 3.1 before 3.1.1 (when Python 3.7+ is used). The intermediate-level directories of the filesystem cache had the system's standard umask rather than 0o077.", "poc": {"reference": ["https://www.oracle.com/security-alerts/cpujan2021.html"], "github": ["https://github.com/404notf0und/CVE-Flow", "https://github.com/Live-Hack-CVE/CVE-2020-24584"]}}