{"id": "CVE-2022-48560", "product": "n/a", "version": "n/a", "vulnerability": ["n/a"], "description": "A use-after-free exists in Python through 3.9 via heappushpop in heapq.", "poc": {"reference": ["https://bugs.python.org/issue39421"], "github": ["No PoCs found on GitHub currently."]}}